# Generated by Django 4.1.7 on 2023-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricesale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
