# Generated by Django 4.1.7 on 2023-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenir', '0002_product_pricesale_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricesale',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
