# Generated by Django 4.1.7 on 2023-04-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenir', '0004_product_new_alter_product_pricesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='suvenir/imgcategory'),
        ),
    ]
