# Generated by Django 4.1.7 on 2023-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvenir', '0005_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
